WARNING | 2021-12-01 22:20:55,677 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: PC
WARNING | 2021-12-01 22:20:55,678 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: ospeed
WARNING | 2021-12-01 22:20:55,682 | cle.loader | For more information about "Symbol was allocated without a known size", see https://docs.angr.io/extending-angr/environment#simdata
Traceback (most recent call last):
  File "paths_constraints_main.py", line 352, in <module>
  File "paths_constraints_main.py", line 348, in main
  File "paths_constraints_main.py", line 188, in generate_dataset
  File "paths_constraints_main.py", line 196, in analyze_binary
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/analyses/analysis.py", line 115, in __call__
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 664, in __init__
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 229, in _analyze
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 377, in _analysis_core_baremetal
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/analyses/forward_analysis/forward_analysis.py", line 395, in _process_job_and_get_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1100, in _get_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1427, in _scan_block
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 1554, in _scan_irsb
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/analyses/cfg/cfg_fast.py", line 3273, in _function_add_node
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/analyses/cfg/cfg_base.py", line 408, in _to_snippet
MemoryError
