ERROR   | 2021-12-02 02:03:35,236 | root     | argument 3: <class 'RecursionError'>: maximum recursion depth exceeded while calling a Python object
ERROR   | 2021-12-02 02:03:35,236 | root     | got an error while analyzing id_cpy
