WARNING | 2021-12-02 02:32:45,158 | cle.backends.externs | Symbol was allocated without a known size; emulation may fail if it is used non-opaquely: optopt
WARNING | 2021-12-02 02:32:45,160 | cle.loader | For more information about "Symbol was allocated without a known size", see https://docs.angr.io/extending-angr/environment#simdata
ERROR   | 2021-12-02 02:55:30,738 | root     | b'out of memory'
ERROR   | 2021-12-02 02:55:30,739 | root     | got an error while analyzing parse_colors
ERROR   | 2021-12-02 02:55:31,371 | root     | 
ERROR   | 2021-12-02 02:55:31,372 | root     | got an error while analyzing color_setup
Fatal Python error: Cannot recover from MemoryErrors while normalizing exceptions.

Current thread 0x00007fd70e1c90c0 (most recent call first):
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/size_resolution_mixin.py", line 28 in load
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/size_resolution_mixin.py", line 80 in load
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/underconstrained_mixin.py", line 23 in load
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/actions_mixin.py", line 13 in load
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/clouseau_mixin.py", line 58 in load
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/bvv_conversion_mixin.py", line 29 in load
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/name_resolution_mixin.py", line 57 in load
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/unwrapper_mixin.py", line 18 in load
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/heavy.py", line 29 in _perform_vex_expr_Load
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/claripy/datalayer.py", line 89 in _perform_vex_expr_Load
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/heavy.py", line 290 in _perform_vex_expr_Load
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/actions.py", line 114 in _perform_vex_expr_Load
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/light.py", line 87 in _handle_vex_expr_Load
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/light.py", line 55 in _handle_vex_expr
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/inspect.py", line 31 in _handle_vex_expr
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/light.py", line 184 in _analyze_vex_stmt_WrTmp_data
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/light.py", line 188 in _handle_vex_stmt_WrTmp
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/light.py", line 51 in _handle_vex_stmt
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/heavy.py", line 204 in _handle_vex_stmt
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/resilience.py", line 36 in inner
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/inspect.py", line 40 in _handle_vex_stmt
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/slicing.py", line 30 in _handle_vex_stmt
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/light.py", line 446 in handle_vex_block
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/inspect.py", line 45 in handle_vex_block
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/actions.py", line 30 in handle_vex_block
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/slicing.py", line 26 in handle_vex_block
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/super_fastpath.py", line 19 in handle_vex_block
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/heavy.py", line 138 in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/soot/engine.py", line 64 in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/unicorn.py", line 169 in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/hook.py", line 54 in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/syscall.py", line 18 in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/failure.py", line 21 in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/engine.py", line 149 in process
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/slicing.py", line 19 in process
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/factory.py", line 60 in successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/sim_manager.py", line 441 in successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/misc/hookset.py", line 80 in __call__
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/exploration_techniques/loop_seer.py", line 98 in successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/misc/hookset.py", line 75 in __call__
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/sim_manager.py", line 402 in step_state
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/sim_manager.py", line 365 in step
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/sim_manager.py", line 280 in run
  File "paths_constraints_main.py", line 48 in analyze_func
  File "paths_constraints_main.py", line 212 in analyze_binary
  File "paths_constraints_main.py", line 188 in generate_dataset
  File "paths_constraints_main.py", line 348 in main
  File "paths_constraints_main.py", line 352 in <module>
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
MemoryError
timeout: the monitored command dumped core
Aborted
