Traceback (most recent call last):
  File "paths_constraints_main.py", line 5, in <module>
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/__init__.py", line 40, in <module>
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/sim_procedure.py", line 6, in <module>
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/cle/__init__.py", line 17, in <module>
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/cle/utils.py", line 4, in <module>
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/cle/errors.py", line 10, in <module>
MemoryError
