--- Logging error ---
Traceback (most recent call last):
  File "paths_constraints_main.py", line 212, in analyze_binary
  File "paths_constraints_main.py", line 48, in analyze_func
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/sim_manager.py", line 280, in run
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/sim_manager.py", line 365, in step
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/sim_manager.py", line 402, in step_state
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/misc/hookset.py", line 75, in __call__
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/exploration_techniques/loop_seer.py", line 98, in successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/misc/hookset.py", line 80, in __call__
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/sim_manager.py", line 441, in successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/factory.py", line 60, in successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/slicing.py", line 19, in process
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/engine.py", line 149, in process
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/failure.py", line 21, in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/syscall.py", line 18, in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/hook.py", line 54, in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/unicorn.py", line 169, in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/soot/engine.py", line 64, in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/heavy.py", line 138, in process_successors
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/super_fastpath.py", line 19, in handle_vex_block
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/slicing.py", line 26, in handle_vex_block
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/actions.py", line 30, in handle_vex_block
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/inspect.py", line 45, in handle_vex_block
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/light.py", line 446, in handle_vex_block
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/slicing.py", line 30, in _handle_vex_stmt
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/inspect.py", line 40, in _handle_vex_stmt
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/resilience.py", line 36, in inner
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/heavy.py", line 204, in _handle_vex_stmt
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/light.py", line 51, in _handle_vex_stmt
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/light/light.py", line 180, in _handle_vex_stmt_Put
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/actions.py", line 155, in _perform_vex_stmt_Put
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/claripy/datalayer.py", line 96, in _perform_vex_stmt_Put
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/engines/vex/heavy/heavy.py", line 32, in _perform_vex_stmt_Put
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/unwrapper_mixin.py", line 11, in store
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/name_resolution_mixin.py", line 50, in store
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/bvv_conversion_mixin.py", line 25, in store
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/simplification_mixin.py", line 11, in store
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/clouseau_mixin.py", line 11, in store
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/actions_mixin.py", line 34, in store
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/underconstrained_mixin.py", line 27, in store
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/size_resolution_mixin.py", line 88, in store
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/size_resolution_mixin.py", line 47, in store
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/address_concretization_mixin.py", line 327, in store
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/address_concretization_mixin.py", line 318, in _store_one_addr
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/actions_mixin.py", line 74, in store
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/conditional_store_mixin.py", line 17, in store
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/convenient_mappings_mixin.py", line 44, in store
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/dirty_addrs_mixin.py", line 8, in store
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/paged_memory/paged_memory_mixin.py", line 169, in store
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/paged_memory/privileged_mixin.py", line 17, in _get_page
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/paged_memory/paged_memory_mixin.py", line 75, in _get_page
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/paged_memory/pages/refcount_mixin.py", line 32, in acquire_unique
  File "/home/ittay.al/venv/pproc/lib/python3.7/site-packages/angr/storage/memory_mixins/paged_memory/pages/ultra_page.py", line 48, in copy
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ittay.al/miniconda3/envs/tf1/lib/python3.7/logging/__init__.py", line 1025, in emit
  File "/home/ittay.al/miniconda3/envs/tf1/lib/python3.7/logging/__init__.py", line 869, in format
  File "/home/ittay.al/miniconda3/envs/tf1/lib/python3.7/logging/__init__.py", line 610, in format
  File "/home/ittay.al/miniconda3/envs/tf1/lib/python3.7/logging/__init__.py", line 550, in formatTime
MemoryError
Call stack:
  File "paths_constraints_main.py", line 352, in <module>
  File "paths_constraints_main.py", line 348, in main
  File "paths_constraints_main.py", line 188, in generate_dataset
  File "paths_constraints_main.py", line 216, in analyze_binary
Message: ''
Arguments: ()
ERROR   | 2021-11-30 15:21:15,553 | root     | got an error while analyzing initialize_exit_failure
ERROR   | 2021-11-30 15:21:15,557 | root     | 
ERROR   | 2021-11-30 15:21:15,557 | root     | got an error while analyzing to_uchar
ERROR   | 2021-11-30 15:21:15,559 | root     | 
ERROR   | 2021-11-30 15:21:15,559 | root     | got an error while analyzing dot_or_dotdot
ERROR   | 2021-11-30 15:21:15,561 | root     | 
ERROR   | 2021-11-30 15:21:15,561 | root     | got an error while analyzing emit_mandatory_arg_note
ERROR   | 2021-11-30 15:21:15,563 | root     | 
ERROR   | 2021-11-30 15:21:15,563 | root     | got an error while analyzing emit_size_note
ERROR   | 2021-11-30 15:21:15,565 | root     | 
ERROR   | 2021-11-30 15:21:15,565 | root     | got an error while analyzing emit_ancillary_info
ERROR   | 2021-11-30 15:21:15,567 | root     | 
ERROR   | 2021-11-30 15:21:15,567 | root     | got an error while analyzing emit_try_help
ERROR   | 2021-11-30 15:21:15,568 | root     | 
ERROR   | 2021-11-30 15:21:15,568 | root     | got an error while analyzing timetostr
ERROR   | 2021-11-30 15:21:15,570 | root     | 
ERROR   | 2021-11-30 15:21:15,570 | root     | got an error while analyzing bad_cast
ERROR   | 2021-11-30 15:21:15,572 | root     | 
ERROR   | 2021-11-30 15:21:15,572 | root     | got an error while analyzing is_ENOTSUP
ERROR   | 2021-11-30 15:21:15,573 | root     | 
ERROR   | 2021-11-30 15:21:15,573 | root     | got an error while analyzing is_smack_enabled
ERROR   | 2021-11-30 15:21:15,575 | root     | 
ERROR   | 2021-11-30 15:21:15,575 | root     | got an error while analyzing dev_ino_push
ERROR   | 2021-11-30 15:21:15,576 | root     | 
ERROR   | 2021-11-30 15:21:15,576 | root     | got an error while analyzing dev_ino_pop
ERROR   | 2021-11-30 15:21:15,577 | root     | 
ERROR   | 2021-11-30 15:21:15,577 | root     | got an error while analyzing dired_dump_obstack
ERROR   | 2021-11-30 15:21:15,579 | root     | 
ERROR   | 2021-11-30 15:21:15,579 | root     | got an error while analyzing abmon_init
ERROR   | 2021-11-30 15:21:15,580 | root     | 
ERROR   | 2021-11-30 15:21:15,580 | root     | got an error while analyzing dev_ino_hash
ERROR   | 2021-11-30 15:21:15,581 | root     | 
ERROR   | 2021-11-30 15:21:15,581 | root     | got an error while analyzing dev_ino_compare
ERROR   | 2021-11-30 15:21:15,582 | root     | 
ERROR   | 2021-11-30 15:21:15,583 | root     | got an error while analyzing dev_ino_free
ERROR   | 2021-11-30 15:21:15,584 | root     | 
ERROR   | 2021-11-30 15:21:15,584 | root     | got an error while analyzing visit_dir
ERROR   | 2021-11-30 15:21:15,585 | root     | 
ERROR   | 2021-11-30 15:21:15,585 | root     | got an error while analyzing free_pending_ent
ERROR   | 2021-11-30 15:21:15,586 | root     | 
ERROR   | 2021-11-30 15:21:15,586 | root     | got an error while analyzing is_colored
ERROR   | 2021-11-30 15:21:15,588 | root     | 
ERROR   | 2021-11-30 15:21:15,588 | root     | got an error while analyzing restore_default_color
ERROR   | 2021-11-30 15:21:15,589 | root     | 
ERROR   | 2021-11-30 15:21:15,589 | root     | got an error while analyzing set_normal_color
ERROR   | 2021-11-30 15:21:15,590 | root     | 
ERROR   | 2021-11-30 15:21:15,590 | root     | got an error while analyzing sighandler
ERROR   | 2021-11-30 15:21:15,592 | root     | 
ERROR   | 2021-11-30 15:21:15,592 | root     | got an error while analyzing stophandler
ERROR   | 2021-11-30 15:21:15,593 | root     | 
ERROR   | 2021-11-30 15:21:15,593 | root     | got an error while analyzing process_signals
ERROR   | 2021-11-30 15:21:15,594 | root     | 
ERROR   | 2021-11-30 15:21:15,594 | root     | got an error while analyzing set_line_length
ERROR   | 2021-11-30 15:21:15,596 | root     | 
ERROR   | 2021-11-30 15:21:15,596 | root     | got an error while analyzing decode_switches
ERROR   | 2021-11-30 15:21:15,597 | root     | 
ERROR   | 2021-11-30 15:21:15,597 | root     | got an error while analyzing get_funky_string
ERROR   | 2021-11-30 15:21:15,598 | root     | 
ERROR   | 2021-11-30 15:21:15,598 | root     | got an error while analyzing known_term_type
ERROR   | 2021-11-30 15:21:15,599 | root     | 
ERROR   | 2021-11-30 15:21:15,599 | root     | got an error while analyzing parse_ls_color
ERROR   | 2021-11-30 15:21:15,601 | root     | 
ERROR   | 2021-11-30 15:21:15,601 | root     | got an error while analyzing getenv_quoting_style
ERROR   | 2021-11-30 15:21:15,602 | root     | 
ERROR   | 2021-11-30 15:21:15,602 | root     | got an error while analyzing set_exit_status
ERROR   | 2021-11-30 15:21:15,603 | root     | 
ERROR   | 2021-11-30 15:21:15,603 | root     | got an error while analyzing file_failure
ERROR   | 2021-11-30 15:21:15,605 | root     | 
ERROR   | 2021-11-30 15:21:15,605 | root     | got an error while analyzing queue_directory
ERROR   | 2021-11-30 15:21:15,606 | root     | 
ERROR   | 2021-11-30 15:21:15,606 | root     | got an error while analyzing print_dir
ERROR   | 2021-11-30 15:21:15,607 | root     | 
ERROR   | 2021-11-30 15:21:15,607 | root     | got an error while analyzing add_ignore_pattern
ERROR   | 2021-11-30 15:21:15,608 | root     | 
ERROR   | 2021-11-30 15:21:15,609 | root     | got an error while analyzing patterns_match
ERROR   | 2021-11-30 15:21:15,610 | root     | 
ERROR   | 2021-11-30 15:21:15,610 | root     | got an error while analyzing file_ignored
ERROR   | 2021-11-30 15:21:15,611 | root     | 
ERROR   | 2021-11-30 15:21:15,611 | root     | got an error while analyzing unsigned_file_size
ERROR   | 2021-11-30 15:21:15,612 | root     | 
ERROR   | 2021-11-30 15:21:15,612 | root     | got an error while analyzing has_capability
ERROR   | 2021-11-30 15:21:15,614 | root     | 
ERROR   | 2021-11-30 15:21:15,614 | root     | got an error while analyzing free_ent
ERROR   | 2021-11-30 15:21:15,615 | root     | 
ERROR   | 2021-11-30 15:21:15,615 | root     | got an error while analyzing clear_files
ERROR   | 2021-11-30 15:21:15,616 | root     | 
ERROR   | 2021-11-30 15:21:15,616 | root     | got an error while analyzing errno_unsupported
ERROR   | 2021-11-30 15:21:15,618 | root     | 
ERROR   | 2021-11-30 15:21:15,618 | root     | got an error while analyzing getfilecon_cache
ERROR   | 2021-11-30 15:21:15,619 | root     | 
ERROR   | 2021-11-30 15:21:15,619 | root     | got an error while analyzing file_has_acl_cache
ERROR   | 2021-11-30 15:21:15,620 | root     | 
ERROR   | 2021-11-30 15:21:15,620 | root     | got an error while analyzing has_capability_cache
ERROR   | 2021-11-30 15:21:15,621 | root     | 
ERROR   | 2021-11-30 15:21:15,621 | root     | got an error while analyzing gobble_file
ERROR   | 2021-11-30 15:21:15,623 | root     | 
ERROR   | 2021-11-30 15:21:15,623 | root     | got an error while analyzing is_directory
ERROR   | 2021-11-30 15:21:15,624 | root     | 
ERROR   | 2021-11-30 15:21:15,624 | root     | got an error while analyzing get_link_name
ERROR   | 2021-11-30 15:21:15,625 | root     | 
ERROR   | 2021-11-30 15:21:15,625 | root     | got an error while analyzing make_link_name
ERROR   | 2021-11-30 15:21:15,627 | root     | 
ERROR   | 2021-11-30 15:21:15,627 | root     | got an error while analyzing basename_is_dot_or_dotdot
ERROR   | 2021-11-30 15:21:15,628 | root     | 
ERROR   | 2021-11-30 15:21:15,628 | root     | got an error while analyzing extract_dirs_from_files
ERROR   | 2021-11-30 15:21:15,629 | root     | 
ERROR   | 2021-11-30 15:21:15,629 | root     | got an error while analyzing xstrcoll
ERROR   | 2021-11-30 15:21:15,631 | root     | 
ERROR   | 2021-11-30 15:21:15,631 | root     | got an error while analyzing cmp_ctime
ERROR   | 2021-11-30 15:21:15,632 | root     | 
ERROR   | 2021-11-30 15:21:15,632 | root     | got an error while analyzing cmp_mtime
ERROR   | 2021-11-30 15:21:15,633 | root     | 
ERROR   | 2021-11-30 15:21:15,633 | root     | got an error while analyzing cmp_atime
ERROR   | 2021-11-30 15:21:15,635 | root     | 
ERROR   | 2021-11-30 15:21:15,635 | root     | got an error while analyzing cmp_size
ERROR   | 2021-11-30 15:21:15,636 | root     | 
ERROR   | 2021-11-30 15:21:15,636 | root     | got an error while analyzing cmp_name
ERROR   | 2021-11-30 15:21:15,637 | root     | 
ERROR   | 2021-11-30 15:21:15,637 | root     | got an error while analyzing cmp_extension
ERROR   | 2021-11-30 15:21:15,639 | root     | 
ERROR   | 2021-11-30 15:21:15,639 | root     | got an error while analyzing xstrcoll_ctime
ERROR   | 2021-11-30 15:21:15,640 | root     | 
ERROR   | 2021-11-30 15:21:15,640 | root     | got an error while analyzing strcmp_ctime
ERROR   | 2021-11-30 15:21:15,641 | root     | 
ERROR   | 2021-11-30 15:21:15,641 | root     | got an error while analyzing rev_xstrcoll_ctime
ERROR   | 2021-11-30 15:21:15,643 | root     | 
ERROR   | 2021-11-30 15:21:15,643 | root     | got an error while analyzing rev_strcmp_ctime
ERROR   | 2021-11-30 15:21:15,644 | root     | 
ERROR   | 2021-11-30 15:21:15,644 | root     | got an error while analyzing xstrcoll_df_ctime
ERROR   | 2021-11-30 15:21:15,645 | root     | 
ERROR   | 2021-11-30 15:21:15,645 | root     | got an error while analyzing strcmp_df_ctime
ERROR   | 2021-11-30 15:21:15,647 | root     | 
ERROR   | 2021-11-30 15:21:15,647 | root     | got an error while analyzing rev_xstrcoll_df_ctime
ERROR   | 2021-11-30 15:21:15,648 | root     | 
ERROR   | 2021-11-30 15:21:15,648 | root     | got an error while analyzing rev_strcmp_df_ctime
ERROR   | 2021-11-30 15:21:15,649 | root     | 
ERROR   | 2021-11-30 15:21:15,650 | root     | got an error while analyzing xstrcoll_mtime
ERROR   | 2021-11-30 15:21:15,651 | root     | 
ERROR   | 2021-11-30 15:21:15,651 | root     | got an error while analyzing strcmp_mtime
ERROR   | 2021-11-30 15:21:15,652 | root     | 
ERROR   | 2021-11-30 15:21:15,652 | root     | got an error while analyzing rev_xstrcoll_mtime
ERROR   | 2021-11-30 15:21:15,653 | root     | 
ERROR   | 2021-11-30 15:21:15,654 | root     | got an error while analyzing rev_strcmp_mtime
ERROR   | 2021-11-30 15:21:15,655 | root     | 
ERROR   | 2021-11-30 15:21:15,655 | root     | got an error while analyzing xstrcoll_df_mtime
ERROR   | 2021-11-30 15:21:15,656 | root     | 
ERROR   | 2021-11-30 15:21:15,656 | root     | got an error while analyzing strcmp_df_mtime
ERROR   | 2021-11-30 15:21:15,658 | root     | 
ERROR   | 2021-11-30 15:21:15,658 | root     | got an error while analyzing rev_xstrcoll_df_mtime
ERROR   | 2021-11-30 15:21:15,659 | root     | 
ERROR   | 2021-11-30 15:21:15,659 | root     | got an error while analyzing rev_strcmp_df_mtime
ERROR   | 2021-11-30 15:21:15,660 | root     | 
ERROR   | 2021-11-30 15:21:15,660 | root     | got an error while analyzing xstrcoll_atime
ERROR   | 2021-11-30 15:21:15,662 | root     | 
ERROR   | 2021-11-30 15:21:15,662 | root     | got an error while analyzing strcmp_atime
ERROR   | 2021-11-30 15:21:15,663 | root     | 
ERROR   | 2021-11-30 15:21:15,663 | root     | got an error while analyzing rev_xstrcoll_atime
ERROR   | 2021-11-30 15:21:15,664 | root     | 
ERROR   | 2021-11-30 15:21:15,664 | root     | got an error while analyzing rev_strcmp_atime
ERROR   | 2021-11-30 15:21:15,666 | root     | 
ERROR   | 2021-11-30 15:21:15,666 | root     | got an error while analyzing xstrcoll_df_atime
ERROR   | 2021-11-30 15:21:15,667 | root     | 
ERROR   | 2021-11-30 15:21:15,667 | root     | got an error while analyzing strcmp_df_atime
ERROR   | 2021-11-30 15:21:15,668 | root     | 
ERROR   | 2021-11-30 15:21:15,668 | root     | got an error while analyzing rev_xstrcoll_df_atime
ERROR   | 2021-11-30 15:21:15,670 | root     | 
ERROR   | 2021-11-30 15:21:15,670 | root     | got an error while analyzing rev_strcmp_df_atime
ERROR   | 2021-11-30 15:21:15,671 | root     | 
ERROR   | 2021-11-30 15:21:15,671 | root     | got an error while analyzing xstrcoll_size
ERROR   | 2021-11-30 15:21:15,672 | root     | 
ERROR   | 2021-11-30 15:21:15,672 | root     | got an error while analyzing strcmp_size
ERROR   | 2021-11-30 15:21:15,674 | root     | 
ERROR   | 2021-11-30 15:21:15,674 | root     | got an error while analyzing rev_xstrcoll_size
ERROR   | 2021-11-30 15:21:15,675 | root     | 
ERROR   | 2021-11-30 15:21:15,675 | root     | got an error while analyzing rev_strcmp_size
ERROR   | 2021-11-30 15:21:15,687 | root     | 
ERROR   | 2021-11-30 15:21:15,687 | root     | got an error while analyzing xstrcoll_df_size
ERROR   | 2021-11-30 15:21:15,688 | root     | 
ERROR   | 2021-11-30 15:21:15,688 | root     | got an error while analyzing strcmp_df_size
ERROR   | 2021-11-30 15:21:15,690 | root     | 
ERROR   | 2021-11-30 15:21:15,690 | root     | got an error while analyzing rev_xstrcoll_df_size
ERROR   | 2021-11-30 15:21:15,691 | root     | 
ERROR   | 2021-11-30 15:21:15,691 | root     | got an error while analyzing rev_strcmp_df_size
ERROR   | 2021-11-30 15:21:15,692 | root     | 
ERROR   | 2021-11-30 15:21:15,692 | root     | got an error while analyzing xstrcoll_name
ERROR   | 2021-11-30 15:21:15,694 | root     | 
ERROR   | 2021-11-30 15:21:15,694 | root     | got an error while analyzing strcmp_name
ERROR   | 2021-11-30 15:21:15,695 | root     | 
ERROR   | 2021-11-30 15:21:15,695 | root     | got an error while analyzing rev_xstrcoll_name
ERROR   | 2021-11-30 15:21:15,704 | root     | 
ERROR   | 2021-11-30 15:21:15,704 | root     | got an error while analyzing rev_strcmp_name
ERROR   | 2021-11-30 15:21:15,705 | root     | 
ERROR   | 2021-11-30 15:21:15,706 | root     | got an error while analyzing xstrcoll_df_name
ERROR   | 2021-11-30 15:21:15,707 | root     | 
ERROR   | 2021-11-30 15:21:15,707 | root     | got an error while analyzing strcmp_df_name
ERROR   | 2021-11-30 15:21:15,708 | root     | 
ERROR   | 2021-11-30 15:21:15,708 | root     | got an error while analyzing rev_xstrcoll_df_name
ERROR   | 2021-11-30 15:21:15,709 | root     | 
ERROR   | 2021-11-30 15:21:15,710 | root     | got an error while analyzing rev_strcmp_df_name
ERROR   | 2021-11-30 15:21:15,711 | root     | 
ERROR   | 2021-11-30 15:21:15,711 | root     | got an error while analyzing xstrcoll_extension
ERROR   | 2021-11-30 15:21:15,712 | root     | 
ERROR   | 2021-11-30 15:21:15,712 | root     | got an error while analyzing strcmp_extension
ERROR   | 2021-11-30 15:21:15,714 | root     | 
ERROR   | 2021-11-30 15:21:15,714 | root     | got an error while analyzing rev_xstrcoll_extension
ERROR   | 2021-11-30 15:21:15,715 | root     | 
ERROR   | 2021-11-30 15:21:15,715 | root     | got an error while analyzing rev_strcmp_extension
ERROR   | 2021-11-30 15:21:15,716 | root     | 
ERROR   | 2021-11-30 15:21:15,716 | root     | got an error while analyzing xstrcoll_df_extension
ERROR   | 2021-11-30 15:21:15,718 | root     | 
ERROR   | 2021-11-30 15:21:15,718 | root     | got an error while analyzing strcmp_df_extension
ERROR   | 2021-11-30 15:21:15,719 | root     | 
ERROR   | 2021-11-30 15:21:15,719 | root     | got an error while analyzing rev_xstrcoll_df_extension
ERROR   | 2021-11-30 15:21:15,720 | root     | 
ERROR   | 2021-11-30 15:21:15,720 | root     | got an error while analyzing rev_strcmp_df_extension
ERROR   | 2021-11-30 15:21:15,722 | root     | 
ERROR   | 2021-11-30 15:21:15,722 | root     | got an error while analyzing cmp_version
ERROR   | 2021-11-30 15:21:15,723 | root     | 
ERROR   | 2021-11-30 15:21:15,723 | root     | got an error while analyzing xstrcoll_version
ERROR   | 2021-11-30 15:21:15,724 | root     | 
ERROR   | 2021-11-30 15:21:15,724 | root     | got an error while analyzing rev_xstrcoll_version
ERROR   | 2021-11-30 15:21:15,726 | root     | 
ERROR   | 2021-11-30 15:21:15,726 | root     | got an error while analyzing xstrcoll_df_version
ERROR   | 2021-11-30 15:21:15,727 | root     | 
ERROR   | 2021-11-30 15:21:15,727 | root     | got an error while analyzing rev_xstrcoll_df_version
ERROR   | 2021-11-30 15:21:15,728 | root     | 
ERROR   | 2021-11-30 15:21:15,728 | root     | got an error while analyzing initialize_ordering_vector
ERROR   | 2021-11-30 15:21:15,730 | root     | 
ERROR   | 2021-11-30 15:21:15,730 | root     | got an error while analyzing sort_files
ERROR   | 2021-11-30 15:21:18,725 | root     | 
ERROR   | 2021-11-30 15:21:19,909 | root     | got an error while analyzing print_current_files
Killed
